spring.application.name=couponcore

# In-memory DB
spring.config.activate.on-profile=test
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# REDIS
spring.redis.host=localhost
spring.redis.port=6380