spring.application.name=couponcore

#spring.config.activate.on-profile=local

# MYSQL
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.username=minjae
spring.datasource.hikari.password=1234

# QueryDSL
jakarta.persistence.jdbc.url=jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8
jakarta.persistence.jdbc.driver=com.mysql.cj.jdbc.Driver
jakarta.persistence.jdbc.user=minjae
jakarta.persistence.jdbc.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6380

server.port=8080